apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
  creationTimestamp: "2024-08-16T08:51:49Z"
  generation: 2
  labels:
    app.kubernetes.io/name: fluent-bit
    argocd.argoproj.io/instance: spore-observability
  name: fluent-bit
  namespace: monitoring
  ownerReferences:
  - apiVersion: fluentbit.fluent.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: FluentBit
    name: fluent-bit
    uid: c857edd3-ec48-4058-8223-6645737d5e17
  resourceVersion: "112082041"
  uid: 6e7f010b-6e51-41e4-a2ee-d8037a0b9e12
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      argocd.argoproj.io/instance: spore-observability
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: fluent-bit
        argocd.argoproj.io/instance: spore-observability
      name: fluent-bit
      namespace: monitoring
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: skyralgroup.jfrog.io/ghcr-io/fluent/fluent-operator/fluent-bit:3.1.5
        imagePullPolicy: IfNotPresent
        name: fluent-bit
        ports:
        - containerPort: 2020
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 25Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluent-bit/config
          name: config
          readOnly: true
        - mountPath: /var/log/containers
          mountPropagation: None
          name: varlibcontainers
          readOnly: true
        - mountPath: /var/log/
          mountPropagation: None
          name: varlogs
          readOnly: true
        - mountPath: /var/log/journal
          mountPropagation: None
          name: systemd
          readOnly: true
        - mountPath: /host/fluent-bit-buffer
          mountPropagation: HostToContainer
          name: host-buffer
        - mountPath: /fluent-bit/tail
          name: positions
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: artifactory-image-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: fluent-bit-config
      - hostPath:
          path: /var/log/containers
          type: ""
        name: varlibcontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlogs
      - hostPath:
          path: /var/log/journal
          type: ""
        name: systemd
      - hostPath:
          path: /tmp/fluent-bit-buffer
          type: ""
        name: host-buffer
      - hostPath:
          path: /var/lib/fluent-bit/
          type: ""
        name: positions
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 11
  desiredNumberScheduled: 11
  numberAvailable: 11
  numberMisscheduled: 0
  numberReady: 11
  observedGeneration: 2
  updatedNumberScheduled: 11